In [13]:
import numpy as np
pointa = np.array([ 387.570679,    -31.266905,    -22.021992














])
eye1 = np.array([  -0.498657  ,     96.470753 ,     693.094727 ])
eye2 =  np.array([  -0.498657  ,     96.470753 ,      693.054596 ])










pointb = np.array([ 409.184418 ,   -35.023827  ,  -23.389391









 ])

a1= pointa-eye1
b2 = pointb-eye2
#a1 = np.array([  412.633032  ,     -124.601751    ,   -719.053852])
#b2 = np.array([  412.633032      , -128.588051  ,     -722.170641   ])
dir1 = a1/np.linalg.norm(a1)
dir2 = b2/np.linalg.norm(b2)
dir1 = np.array([0.09312,	0.24567	,-0.9641
])
dir2 = np.array([0.01984,	0.24567,	-0.968765
])
print(dir1,dir2)














dot = np.dot(dir1, dir2)
'''
dotb = np.dot(a, b)
n1 = np.linalg.norm(dir1)
n2 = np.linalg.norm(dir2)
n3 = np.linalg.norm(b)
cos = dot / (n1 * n2)
cosb = dotb / (n2 * n3)'
'''
angl = np.arccos(np.clip(dot,-1,1))
#anglb = np.arccos(np.clip(cosb,-1,1))
dega = np.degrees(angl)
#degb = np.degrees(anglb)
#vel3 = abs(angl - anglb) / 0.02
vel1 = dega/0.0167
#vel2 = degb/0.017
print(vel1)
dega


[ 0.09312  0.24567 -0.9641 ] [ 0.01984   0.24567  -0.968765]
299.68102672125127


5.004673146244897

In [5]:
import numpy as np
a = np.array([-185.7,	370.5,	-723.7













])
b = np.array([-223.2,	381.9	,-715.2















])




s =a/np.linalg.norm(a)
s2 = b/np.linalg.norm(b)
print(s2)
print(np.mean([s, s2], axis=0))

[-0.26541787  0.45413568 -0.85047877]
[-0.24404464  0.44919966 -0.85913087]


In [10]:
import numpy as np

def velocity_px_to_deg(x1, y1, x2, y2, delta_t, screen_width_px, screen_width_cm, screen_distance_cm):
    """
    Converts gaze velocity from pixels/sec to degrees/sec.
    
    Parameters:
        x1, y1: Coordinates of gaze point at time t1 (in pixels)
        x2, y2: Coordinates of gaze point at time t2 (in pixels)
        delta_t: Time difference between two samples (in seconds)
        screen_width_px: Screen width in pixels
        screen_width_cm: Screen width in centimeters
        screen_distance_cm: Distance from eyes to screen in centimeters
    
    Returns:
        velocity in degrees per second (°/s)
    """
    # Convert pixel distance to cm using screen width
    px_per_cm = screen_width_px / screen_width_cm

    # Compute Euclidean distance in pixels
    d_px = np.sqrt((x2 - x1) ** 2 + (y2 - y1) ** 2)

    # Convert pixel distance to cm
    #d_cm = d_px / px_per_cm

    # Compute visual angle in degrees
    theta = 2 * np.arctan((d_px) / (2*screen_distance_cm)) 
    ang = np.degrees(theta)

    # Compute velocity in °/s
    velocity_deg_per_sec = ang / delta_t if delta_t > 0 else 0

    return velocity_deg_per_sec

velocity_px_to_deg(391.75    ,    293.95,

322.45  ,      220.10,

0.034,1920,70.7,681.65)


249.9084501984771

In [38]:
eye_pos = np.round(np.array([-0.26134,0.449315,	-0.853275]))
dire = np.array([-0.26134,0.449315,	-0.853275])
gaze_p = eye_pos+dire*717.4
eye_pos

array([-0.,  0., -1.])

In [12]:
a = np.array([18.7	,362.2,0])

b = np.array([ 21.85	,358.2,0])

d_px = np.linalg.norm(a-b)
screen_distance_cm = 600
theta = 2 * np.arctan((d_px) / (2*screen_distance_cm)) 
ang = np.degrees(theta)
ang/0.017

28.59949049891405